name: Main Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: ["ubuntu-latest", "windows-latest"]
    name: Build python ${{ matrix.python }} environment on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install pipx
        run: python -m pip install pipx

      - name: Install pdm
        run: pipx install pdm

      - name: Install dependencies
        run: pdm install --group dev

      - name: Run tests
        run: pdm run pytest
